---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-04e59c05167ea7bd5"
  module_defaults:
    group/aws:
      region: "us-west-1"
  tasks:
    - name: ansible EC2 instance 
      ec2:
        key_name: koh
        group: Module5-developer-sg
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags: 
          Name: Module5 ansible
          Module: 5
        wait: yes
        assign_public_ip: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        exact_count: 1
        count_tag:
          Name: Module5 ansible